# Generated by Django 2.1.3 on 2019-01-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parseanddownload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talksdata',
            old_name='MessageBody',
            new_name='Message_body',
        ),
    ]
